language: java
before_script:
  - unset GEM_PATH GEM_HOME IRBRC
  - "export PATH=`pwd`/bin:$PATH"
  - jdk_switcher use $TRAVIS_JDK_VERSION

jdk:
  - oraclejdk7

os:
  - linux
  - osx

env:
  matrix:
    - TARGET='-Ptruffle'

matrix:

before_install:
  - git fetch --tags
  - ./set_up_jdk_switcher.rb
  - grep sudo $HOME/.jdk_switcher_rc || true
  - source $HOME/.jdk_switcher_rc
  - if [[ $TRAVIS_JDK_VERSION = 'oraclejdk8' ]]; then sudo apt-get update; sudo apt-get install oracle-java8-installer; else true; fi

# the install stores the artifact in the localrepo for
# the second maven run with $TARGET
script: java -version; ( mvn install -Pbootstrap | grep -v Down ) && mvn -Dinvoker.skip=false $TARGET
install: /bin/true
notifications:
  irc:
    channels:
      - "irc.freenode.org#jruby"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"

# we are on a branch
    #on_success: always
    on_failure: never
